<?php
/**
 * Implements hook_FORM_ID_alter
 * 
 * 登录form修改，用于增加openid
 * 
 * @param unknown $form
 * @param unknown $form_state
 * @param unknown $form_id
 */
function linkfreelife_form_user_login_alter(&$form, &$form_state, $form_id){
	$openid = $_REQUEST['openid'];
	if(isset($openid)){
		$form['openid'] = array(
		    '#type' => 'textfield',
		    '#title' => t("weixin openid"),
			'#disabled' => TRUE,
		    '#required' => TRUE,
			'#default_value' =>$openid,
	  	);
	}
}

/**
 * Impements hook_user_login
 * 
 * @param unknown $edit
 * @param unknown $account
 */
function linkfreelife_user_login(&$edit, $account) {
	if(isset($edit['values']['openid'])){
		//判断是否是手机通过openid登录
		rules_invoke_component('rules_r001',$edit['values']['openid']);
	}
}
?>